project_id = "rwqteupkdkkmigvajdrv"

[functions.gemini-chat]
verify_jwt = false

[functions.openai-chat]
verify_jwt = false

[functions.document-analyzer]
verify_jwt = false

[functions.quiz-generator]
verify_jwt = false

[functions.study-planner]
verify_jwt = false

[functions.code-generator]
verify_jwt = false

[functions.code-generator-gemini]
verify_jwt = true

[functions.generate-image]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.room-chat]
verify_jwt = true