project_id = "rwqteupkdkkmigvajdrv"

[functions.code-runner]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.openai-chat]
verify_jwt = false

[functions.document-analyzer]
verify_jwt = false

[functions.quiz-generator]
verify_jwt = false

[functions.study-planner]
verify_jwt = false

[functions.code-generator]
verify_jwt = false

[functions.code-generator-gemini]
verify_jwt = true

[functions.generate-image]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.room-chat]
verify_jwt = true

[functions.publish-website]
verify_jwt = true

[functions.serve-website]
verify_jwt = false

[functions.crop-analyzer]
verify_jwt = false

[functions.crop-chat]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.code-assistant]
verify_jwt = true

[functions.haq-jaano-ai]
verify_jwt = false

[functions.deploy-to-netlify]
verify_jwt = false
