import { useState } from 'react';

const translations = {
  en: {
    appName: 'Vithal AI Assistant',
    tagline: 'Advanced AI-Powered Career Intelligence Platform',
    heroTitle: 'Transform Your Career Journey with AI Excellence',
    heroSubtitle: 'Leverage cutting-edge artificial intelligence for strategic career planning, comprehensive skill assessment, and data-driven professional development tailored for ambitious Indian professionals',
    getStarted: 'Launch AI Assistant',
    learnMore: 'Explore Platform',
    howItWorks: 'Our Technology',
    features: 'Platform Features',
    testimonials: 'Success Stories',
    contact: 'Connect With Us',
    step1Title: 'Intelligent Profile Assessment',
    step1Desc: 'Our AI conducts comprehensive analysis of your skills, interests, educational background, and career objectives',
    step2Title: 'Advanced AI Processing',
    step2Desc: 'Machine learning algorithms analyze market trends, industry demands, and career trajectories to match your profile',
    step3Title: 'Strategic Career Roadmap',
    step3Desc: 'Receive detailed career paths, skill development strategies, and personalized learning recommendations',
    feature1Title: 'Next-Gen AI Career Guidance',
    feature1Desc: 'Powered by Google Gemini AI for sophisticated career intelligence and strategic planning',
    feature2Title: 'Real-Time Market Intelligence',
    feature2Desc: 'Live industry analysis, salary insights, placement data, and emerging opportunity identification',
    feature3Title: 'Personalized Learning Ecosystem',
    feature3Desc: 'Curated course recommendations, skill gap analysis, and professional development pathways',
    startAssessment: 'Begin AI Career Analysis',
    readyToStart: 'Ready to Accelerate Your Career?',
    joinThousands: 'Join thousands of ambitious Indian professionals who have transformed their careers with Vithal AI',
    startNow: 'Start Your Assessment Now',
    madeBy: 'Engineered by Shree Alankar',
    poweredBy: 'Powered by Google Gemini AI',
    professionalDescription: 'Empowering Indian Professionals with Advanced AI-Driven Career Intelligence.',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    login: 'Login',
    signup: 'Sign Up',
    or: 'or'
  },
  hi: {
    appName: 'विठल AI असिस्टेंट',
    tagline: 'अत्याधुनिक AI-संचालित करियर इंटेलिजेंस प्लेटफॉर्म',
    heroTitle: 'AI उत्कृष्टता के साथ अपनी करियर यात्रा को रूपांतरित करें',
    heroSubtitle: 'रणनीतिक करियर योजना, व्यापक कौशल मूल्यांकन, और महत्वाकांक्षी भारतीय पेशेवरों के लिए डेटा-संचालित व्यावसायिक विकास के लिए अत्याधुनिक आर्टिफिशियल इंटेलिजेंस का लाभ उठाएं',
    getStarted: 'AI असिस्टेंट लॉन्च करें',
    learnMore: 'प्लेटफॉर्म एक्सप्लोर करें',
    howItWorks: 'हमारी तकनीक',
    features: 'प्लेटफॉर्म विशेषताएं',
    testimonials: 'सफलता की कहानियां',
    contact: 'हमसे जुड़ें',
    step1Title: 'बुद्धिमान प्रोफाइल मूल्यांकन',
    step1Desc: 'हमारी AI आपके कौशल, रुचियों, शैक्षिक पृष्ठभूमि और करियर उद्देश्यों का व्यापक विश्लेषण करती है',
    step2Title: 'उन्नत AI प्रसंस्करण',
    step2Desc: 'मशीन लर्निंग एल्गोरिदम बाजार के रुझान, उद्योग की मांग और करियर प्रक्षेप पथ का विश्लेषण करके आपकी प्रोफाइल से मेल खाते हैं',
    step3Title: 'रणनीतिक करियर रोडमैप',
    step3Desc: 'विस्तृत करियर पथ, कौशल विकास रणनीतियां और व्यक्तिगत शिक्षा सिफारिशें प्राप्त करें',
    feature1Title: 'नेक्स्ट-जेन AI करियर मार्गदर्शन',
    feature1Desc: 'परिष्कृत करियर इंटेलिजेंस और रणनीतिक योजना के लिए Google Gemini AI द्वारा संचालित',
    feature2Title: 'वास्तविक समय बाजार इंटेलिजेंस',
    feature2Desc: 'लाइव उद्योग विश्लेषण, वेतन अंतर्दृष्टि, प्लेसमेंट डेटा और उभरते अवसर की पहचान',
    feature3Title: 'व्यक्तिगत शिक्षा पारिस्थितिकी तंत्र',
    feature3Desc: 'क्यूरेटेड कोर्स सिफारिशें, कौशल अंतर विश्लेषण और व्यावसायिक विकास मार्ग',
    startAssessment: 'AI करियर विश्लेषण शुरू करें',
    readyToStart: 'अपने करियर को तेज़ करने के लिए तैयार हैं?',
    joinThousands: 'हजारों महत्वाकांक्षी भारतीय पेशेवरों में शामिल हों जिन्होंने विठल AI के साथ अपने करियर को रूपांतरित किया है',
    startNow: 'अपना मूल्यांकन अभी शुरू करें',
    madeBy: 'श्री अलंकार द्वारा इंजीनियर्ड',
    poweredBy: 'Google Gemini AI द्वारा संचालित',
    professionalDescription: 'उन्नत AI-संचालित करियर इंटेलिजेंस के साथ भारतीय पेशेवरों को सशक्त बनाना।',
    emailPlaceholder: 'अपना ईमेल दर्ज करें',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    login: 'लॉगिन',
    signup: 'साइन अप',
    or: 'या'
  },
  mr: {
    appName: 'विठल AI असिस्टंट',
    tagline: 'अत्याधुनिक AI-चालित करिअर इंटेलिजेंस प्लॅटफॉर्म',
    heroTitle: 'AI उत्कृष्टतेसह तुमचा करिअर प्रवास रूपांतरित करा',
    heroSubtitle: 'धोरणात्मक करिअर नियोजन, सर्वसमावेशक कौशल्य मूल्यांकन आणि महत्वाकांक्षी भारतीय व्यावसायिकांसाठी डेटा-चालित व्यावसायिक विकासासाठी अत्याधुनिक आर्टिफिशियल इंटेलिजेंसचा लाभ उचला',
    getStarted: 'AI असिस्टंट लॉन्च करा',
    learnMore: 'प्लॅटफॉर्म एक्सप्लोर करा',
    howItWorks: 'आमचे तंत्रज्ञान',
    features: 'प्लॅटफॉर्म वैशिष्ट्ये',
    testimonials: 'यशाच्या कथा',
    contact: 'आमच्याशी जुडा',
    step1Title: 'बुद्धिमान प्रोफाइल मूल्यांकन',
    step1Desc: 'आमची AI तुमची कौशल्ये, आवडी, शैक्षणिक पार्श्वभूमी आणि करिअर उद्दिष्टांचे सर्वसमावेशक विश्लेषण करते',
    step2Title: 'प्रगत AI प्रक्रिया',
    step2Desc: 'मशिन लर्निंग अल्गोरिदम बाजार प्रवृत्ती, उद्योग मागणी आणि करिअर प्रक्षेपणाचे विश्लेषण करून तुमच्या प्रोफाइलशी जुळवतात',
    step3Title: 'धोरणात्मक करिअर रोडमॅप',
    step3Desc: 'तपशीलवार करिअर मार्ग, कौशल्य विकास धोरणे आणि वैयक्तिक शिक्षण शिफारसी प्राप्त करा',
    feature1Title: 'नेक्स्ट-जेन AI करिअर मार्गदर्शन',
    feature1Desc: 'परिष्कृत करिअर इंटेलिजेंस आणि धोरणात्मक नियोजनासाठी Google Gemini AI द्वारे चालित',
    feature2Title: 'रिअल-टाइम मार्केट इंटेलिजेंस',
    feature2Desc: 'लाइव्ह उद्योग विश्लेषण, पगार अंतर्दृष्टी, प्लेसमेंट डेटा आणि उदयोन्मुख संधी ओळख',
    feature3Title: 'वैयक्तिक शिक्षण इकोसिस्टम',
    feature3Desc: 'क्युरेटेड कोर्स शिफारसी, कौशल्य अंतर विश्लेषण आणि व्यावसायिक विकास मार्ग',
    startAssessment: 'AI करिअर विश्लेषण सुरू करा',
    readyToStart: 'तुमचा करिअर वेगवान करण्यासाठी तयार आहात?',
    joinThousands: 'हजारो महत्वाकांक्षी भारतीय व्यावसायिकांमध्ये सामिल व्हा ज्यांनी विठल AI सह त्यांचा करिअर रूपांतरित केला आहे',
    startNow: 'तुमचे मूल्यांकन आता सुरू करा',
    madeBy: 'श्री अलंकार यांनी इंजिनियर केलेले',
    poweredBy: 'Google Gemini AI द्वारे चालित',
    professionalDescription: 'प्रगत AI-चालित करिअर इंटेलिजेंससह भारतीय व्यावसायिकांना सशक्त बनवणे।',
    emailPlaceholder: 'तुमचा ईमेल प्रविष्ट करा',
    passwordPlaceholder: 'तुमचा पासवर्ड प्रविष्ट करा',
    login: 'लॉगिन',
    signup: 'साइन अप',
    or: 'किंवा'
  }
};

export const useLanguage = () => {
  const [language, setLanguage] = useState<'en' | 'hi' | 'mr'>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return {
    language,
    setLanguage,
    t
  };
};