import { useGlobalLanguage } from '@/contexts/LanguageContext';

const translations = {
  en: {
    appName: 'Vithal AI Assistant',
    tagline: 'Advanced AI-Powered Career Intelligence Platform',
    heroTitle: 'Transform Your Career Journey with AI Excellence',
    heroSubtitle: 'Leverage cutting-edge artificial intelligence for strategic career planning, comprehensive skill assessment, and data-driven professional development tailored for ambitious Indian professionals',
    heroDescription: 'Empowering students and professionals with AI-powered learning, intelligent code generation, collaborative study rooms, and smart agricultural analysis tools.',
    getStarted: 'Launch AI Assistant',
    learnMore: 'Explore Platform',
    howItWorks: 'Our Technology',
    features: 'Platform Features',
    testimonials: 'Success Stories',
    contact: 'Connect With Us',
    step1Title: 'Intelligent Profile Assessment',
    step1Desc: 'Our AI conducts comprehensive analysis of your skills, interests, educational background, and career objectives',
    step2Title: 'Advanced AI Processing',
    step2Desc: 'Machine learning algorithms analyze market trends, industry demands, and career trajectories to match your profile',
    step3Title: 'Strategic Career Roadmap',
    step3Desc: 'Receive detailed career paths, skill development strategies, and personalized learning recommendations',
    feature1Title: 'Next-Gen AI Career Guidance',
    feature1Desc: 'Powered by Google Gemini AI for sophisticated career intelligence and strategic planning',
    feature2Title: 'Real-Time Market Intelligence',
    feature2Desc: 'Live industry analysis, salary insights, placement data, and emerging opportunity identification',
    feature3Title: 'Personalized Learning Ecosystem',
    feature3Desc: 'Curated course recommendations, skill gap analysis, and professional development pathways',
    feature4Title: 'Indian Youth Focus',
    feature4Desc: 'Specially designed for Indian job market and cultural context',
    feature5Title: 'Multi-language Support',
    feature5Desc: 'Available in English, Hindi, and Marathi for better accessibility',
    feature6Title: 'Career Success',
    feature6Desc: 'Track your progress and celebrate your career milestones',
    startAssessment: 'Begin AI Career Analysis',
    readyToStart: 'Ready to Accelerate Your Career?',
    joinThousands: 'Join thousands of ambitious Indian professionals who have transformed their careers with Vithal AI',
    startNow: 'Start Your Assessment Now',
    madeBy: 'Engineered by Shree Alankar',
    poweredBy: 'Powered by Google Gemini AI',
    professionalDescription: 'Empowering Indian Professionals with Advanced AI-Driven Career Intelligence.',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    login: 'Login',
    signup: 'Sign Up',
    or: 'or',
    // New translations for hero section
    multiModalAI: 'Multi-Modal AI',
    multiModalDesc: 'Ask questions via text, voice, or upload images for instant AI-powered solutions',
    studyHelper: 'Study Helper',
    studyHelperDesc: 'Get help with homework, solve math problems, and clear academic doubts instantly',
    latestCourses: 'Latest Courses',
    latestCoursesDesc: 'Get personalized course recommendations with verified 2024-2025 content',
    howItWorksExp: 'Experience our advanced AI-powered career intelligence platform designed for strategic professional development',
    // Settings
    profile: 'Profile',
    logout: 'Logout',
    language: 'Language',
    settings: 'Settings',
    copyright: '© 2025 Vithal AI Assistant. Empowering Indian Professionals with Advanced AI-Driven Career Intelligence.',
    // Chat interface
    chat: 'Chat',
    code: 'Code',
    cropAnalyzer: 'Crop Analyzer',
    studyRooms: 'Study Rooms',
    typeMessage: 'Type your message...',
    send: 'Send',
    newChat: 'New Chat',
    recentChats: 'Recent Chats',
    deleteHistory: 'Delete History',
    // Code generator
    codeGenerator: 'Code Generator',
    generateCode: 'Generate Code',
    selectLanguage: 'Select Language',
    codeLibrary: 'Code Library',
    // Study rooms
    createRoom: 'Create Room',
    joinRoom: 'Join Room',
    roomName: 'Room Name',
    inviteCode: 'Invite Code',
    members: 'Members',
    notes: 'Notes',
    leaveRoom: 'Leave Room',
    inviteMember: 'Invite Member'
  },
  hi: {
    appName: 'विठल AI असिस्टेंट',
    tagline: 'अत्याधुनिक AI-संचालित करियर इंटेलिजेंस प्लेटफॉर्म',
    heroTitle: 'AI उत्कृष्टता के साथ अपनी करियर यात्रा को रूपांतरित करें',
    heroSubtitle: 'रणनीतिक करियर योजना, व्यापक कौशल मूल्यांकन, और महत्वाकांक्षी भारतीय पेशेवरों के लिए डेटा-संचालित व्यावसायिक विकास के लिए अत्याधुनिक आर्टिफिशियल इंटेलिजेंस का लाभ उठाएं',
    heroDescription: 'AI-संचालित शिक्षण, बुद्धिमान कोड जनरेशन, सहयोगी स्टडी रूम और स्मार्ट कृषि विश्लेषण टूल के साथ छात्रों और पेशेवरों को सशक्त बनाना।',
    getStarted: 'AI असिस्टेंट लॉन्च करें',
    learnMore: 'प्लेटफॉर्म एक्सप्लोर करें',
    howItWorks: 'हमारी तकनीक',
    features: 'प्लेटफॉर्म विशेषताएं',
    testimonials: 'सफलता की कहानियां',
    contact: 'हमसे जुड़ें',
    step1Title: 'बुद्धिमान प्रोफाइल मूल्यांकन',
    step1Desc: 'हमारी AI आपके कौशल, रुचियों, शैक्षिक पृष्ठभूमि और करियर उद्देश्यों का व्यापक विश्लेषण करती है',
    step2Title: 'उन्नत AI प्रसंस्करण',
    step2Desc: 'मशीन लर्निंग एल्गोरिदम बाजार के रुझान, उद्योग की मांग और करियर प्रक्षेप पथ का विश्लेषण करके आपकी प्रोफाइल से मेल खाते हैं',
    step3Title: 'रणनीतिक करियर रोडमैप',
    step3Desc: 'विस्तृत करियर पथ, कौशल विकास रणनीतियां और व्यक्तिगत शिक्षा सिफारिशें प्राप्त करें',
    feature1Title: 'नेक्स्ट-जेन AI करियर मार्गदर्शन',
    feature1Desc: 'परिष्कृत करियर इंटेलिजेंस और रणनीतिक योजना के लिए Google Gemini AI द्वारा संचालित',
    feature2Title: 'वास्तविक समय बाजार इंटेलिजेंस',
    feature2Desc: 'लाइव उद्योग विश्लेषण, वेतन अंतर्दृष्टि, प्लेसमेंट डेटा और उभरते अवसर की पहचान',
    feature3Title: 'व्यक्तिगत शिक्षा पारिस्थितिकी तंत्र',
    feature3Desc: 'क्यूरेटेड कोर्स सिफारिशें, कौशल अंतर विश्लेषण और व्यावसायिक विकास मार्ग',
    startAssessment: 'AI करियर विश्लेषण शुरू करें',
    readyToStart: 'अपने करियर को तेज़ करने के लिए तैयार हैं?',
    joinThousands: 'हजारों महत्वाकांक्षी भारतीय पेशेवरों में शामिल हों जिन्होंने विठल AI के साथ अपने करियर को रूपांतरित किया है',
    startNow: 'अपना मूल्यांकन अभी शुरू करें',
    madeBy: 'श्री अलंकार द्वारा इंजीनियर्ड',
    poweredBy: 'Google Gemini AI द्वारा संचालित',
    professionalDescription: 'उन्नत AI-संचालित करियर इंटेलिजेंस के साथ भारतीय पेशेवरों को सशक्त बनाना।',
    emailPlaceholder: 'अपना ईमेल दर्ज करें',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    login: 'लॉगिन',
    signup: 'साइन अप',
    or: 'या',
    // New translations
    multiModalAI: 'मल्टी-मोडल AI',
    multiModalDesc: 'तत्काल AI-संचालित समाधान के लिए टेक्स्ट, वॉयस या छवियों के माध्यम से प्रश्न पूछें',
    studyHelper: 'अध्ययन सहायक',
    studyHelperDesc: 'होमवर्क में मदद पाएं, गणित की समस्याओं को हल करें और तुरंत शैक्षणिक संदेह दूर करें',
    latestCourses: 'नवीनतम कोर्स',
    latestCoursesDesc: 'सत्यापित 2024-2025 सामग्री के साथ व्यक्तिगत कोर्स सिफारिशें प्राप्त करें',
    howItWorksExp: 'रणनीतिक व्यावसायिक विकास के लिए डिज़ाइन किए गए हमारे उन्नत AI-संचालित करियर इंटेलिजेंस प्लेटफॉर्म का अनुभव करें',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉगआउट',
    language: 'भाषा',
    settings: 'सेटिंग्स',
    copyright: '© 2025 विठल AI असिस्टेंट। उन्नत AI-संचालित करियर इंटेलिजेंस के साथ भारतीय पेशेवरों को सशक्त बनाना।',
    // Chat interface
    chat: 'चैट',
    code: 'कोड',
    cropAnalyzer: 'फसल विश्लेषक',
    studyRooms: 'स्टडी रूम्स',
    typeMessage: 'अपना संदेश लिखें...',
    send: 'भेजें',
    newChat: 'नई चैट',
    recentChats: 'हाल की चैट्स',
    deleteHistory: 'इतिहास हटाएं',
    // Code generator
    codeGenerator: 'कोड जेनरेटर',
    generateCode: 'कोड जेनरेट करें',
    selectLanguage: 'भाषा चुनें',
    codeLibrary: 'कोड लाइब्रेरी',
    // Study rooms
    createRoom: 'रूम बनाएं',
    joinRoom: 'रूम में शामिल हों',
    roomName: 'रूम का नाम',
    inviteCode: 'आमंत्रण कोड',
    members: 'सदस्य',
    notes: 'नोट्स',
    leaveRoom: 'रूम छोड़ें',
    inviteMember: 'सदस्य आमंत्रित करें'
  },
  mr: {
    appName: 'विठल AI असिस्टंट',
    tagline: 'अत्याधुनिक AI-चालित करिअर इंटेलिजेंस प्लॅटफॉर्म',
    heroTitle: 'AI उत्कृष्टतेसह तुमचा करिअर प्रवास रूपांतरित करा',
    heroSubtitle: 'धोरणात्मक करिअर नियोजन, सर्वसमावेशक कौशल्य मूल्यांकन आणि महत्वाकांक्षी भारतीय व्यावसायिकांसाठी डेटा-चालित व्यावसायिक विकासासाठी अत्याधुनिक आर्टिफिशियल इंटेलिजेंसचा लाभ उचला',
    heroDescription: 'AI-संचालित शिक्षण, बुद्धिमान कोड जनरेशन, सहयोगी स्टडी रूम आणि स्मार्ट कृषी विश्लेषण साधनांसह विद्यार्थी आणि व्यावसायिकांना सक्षम बनवणे।',
    getStarted: 'AI असिस्टंट लॉन्च करा',
    learnMore: 'प्लॅटफॉर्म एक्सप्लोर करा',
    howItWorks: 'आमचे तंत्रज्ञान',
    features: 'प्लॅटफॉर्म वैशिष्ट्ये',
    testimonials: 'यशाच्या कथा',
    contact: 'आमच्याशी जुडा',
    step1Title: 'बुद्धिमान प्रोफाइल मूल्यांकन',
    step1Desc: 'आमची AI तुमची कौशल्ये, आवडी, शैक्षणिक पार्श्वभूमी आणि करिअर उद्दिष्टांचे सर्वसमावेशक विश्लेषण करते',
    step2Title: 'प्रगत AI प्रक्रिया',
    step2Desc: 'मशिन लर्निंग अल्गोरिदम बाजार प्रवृत्ती, उद्योग मागणी आणि करिअर प्रक्षेपणाचे विश्लेषण करून तुमच्या प्रोफाइलशी जुळवतात',
    step3Title: 'धोरणात्मक करिअर रोडमॅप',
    step3Desc: 'तपशीलवार करिअर मार्ग, कौशल्य विकास धोरणे आणि वैयक्तिक शिक्षण शिफारसी प्राप्त करा',
    feature1Title: 'नेक्स्ट-जेन AI करिअर मार्गदर्शन',
    feature1Desc: 'परिष्कृत करिअर इंटेलिजेंस आणि धोरणात्मक नियोजनासाठी Google Gemini AI द्वारे चालित',
    feature2Title: 'रिअल-टाइम मार्केट इंटेलिजेंस',
    feature2Desc: 'लाइव्ह उद्योग विश्लेषण, पगार अंतर्दृष्टी, प्लेसमेंट डेटा आणि उदयोन्मुख संधी ओळख',
    feature3Title: 'वैयक्तिक शिक्षण इकोसिस्टम',
    feature3Desc: 'क्युरेटेड कोर्स शिफारसी, कौशल्य अंतर विश्लेषण आणि व्यावसायिक विकास मार्ग',
    startAssessment: 'AI करिअर विश्लेषण सुरू करा',
    readyToStart: 'तुमचा करिअर वेगवान करण्यासाठी तयार आहात?',
    joinThousands: 'हजारो महत्वाकांक्षी भारतीय व्यावसायिकांमध्ये सामिल व्हा ज्यांनी विठल AI सह त्यांचा करिअर रूपांतरित केला आहे',
    startNow: 'तुमचे मूल्यांकन आता सुरू करा',
    madeBy: 'श्री अलंकार यांनी इंजिनियर केलेले',
    poweredBy: 'Google Gemini AI द्वारे चालित',
    professionalDescription: 'प्रगत AI-चालित करिअर इंटेलिजेंससह भारतीय व्यावसायिकांना सशक्त बनवणे।',
    emailPlaceholder: 'तुमचा ईमेल प्रविष्ट करा',
    passwordPlaceholder: 'तुमचा पासवर्ड प्रविष्ट करा',
    login: 'लॉगिन',
    signup: 'साइन अप',
    or: 'किंवा',
    // New translations
    multiModalAI: 'मल्टी-मोडल AI',
    multiModalDesc: 'तात्काळ AI-संचालित समाधानांसाठी मजकूर, आवाज किंवा प्रतिमांद्वारे प्रश्न विचारा',
    studyHelper: 'अभ्यास सहाय्यक',
    studyHelperDesc: 'गृहकार्यात मदत मिळवा, गणित समस्या सोडवा आणि तात्काळ शैक्षणिक शंका दूर करा',
    latestCourses: 'नवीनतम अभ्यासक्रम',
    latestCoursesDesc: 'सत्यापित 2024-2025 सामग्रीसह वैयक्तिक अभ्यासक्रम शिफारसी मिळवा',
    howItWorksExp: 'धोरणात्मक व्यावसायिक विकासासाठी डिझाइन केलेल्या आमच्या प्रगत AI-संचालित करिअर इंटेलिजेंस प्लॅटफॉर्मचा अनुभव घ्या',
    profile: 'प्रोफाइल',
    logout: 'लॉगआउट',
    language: 'भाषा',
    settings: 'सेटिंग्ज',
    copyright: '© 2025 विठल AI असिस्टंट। प्रगत AI-चालित करिअर इंटेलिजेंससह भारतीय व्यावसायिकांना सशक्त बनवणे।',
    // Chat interface
    chat: 'चॅट',
    code: 'कोड',
    cropAnalyzer: 'पीक विश्लेषक',
    studyRooms: 'स्टडी रूम्स',
    typeMessage: 'तुमचा संदेश लिहा...',
    send: 'पाठवा',
    newChat: 'नवीन चॅट',
    recentChats: 'अलीकडील चॅट्स',
    deleteHistory: 'इतिहास हटवा',
    // Code generator
    codeGenerator: 'कोड जनरेटर',
    generateCode: 'कोड तयार करा',
    selectLanguage: 'भाषा निवडा',
    codeLibrary: 'कोड लायब्ररी',
    // Study rooms
    createRoom: 'रूम तयार करा',
    joinRoom: 'रूममध्ये सामील व्हा',
    roomName: 'रूमचे नाव',
    inviteCode: 'आमंत्रण कोड',
    members: 'सदस्य',
    notes: 'नोट्स',
    leaveRoom: 'रूम सोडा',
    inviteMember: 'सदस्याला आमंत्रित करा'
  }
};

export const useLanguage = () => {
  const { language, setLanguage } = useGlobalLanguage();

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return {
    language,
    setLanguage,
    t
  };
};