import React, { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Users, Plus, Lock, Copy, Check, Share2 } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';
import { StudyRoomInterface } from './study-room-interface';

interface Room {
  id: string;
  name: string;
  description: string | null;
  is_public: boolean;
  created_at: string;
  member_count?: number;
}

export const StudyRooms: React.FC<{ user: any }> = ({ user }) => {
  const [rooms, setRooms] = useState<Room[]>([]);
  const [selectedRoom, setSelectedRoom] = useState<Room | null>(null);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [isJoinOpen, setIsJoinOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  const [showInviteDialog, setShowInviteDialog] = useState(false);
  const [currentInviteCode, setCurrentInviteCode] = useState<string>('');
  const { toast } = useToast();

  // Form states
  const [roomName, setRoomName] = useState('');
  const [roomDescription, setRoomDescription] = useState('');

  useEffect(() => {
    loadRooms();
  }, []);

  const loadRooms = async () => {
    try {
      // Get only rooms user is a member of (RLS handles this automatically)
      const { data: memberRooms } = await supabase
        .from('room_members')
        .select('room_id, study_rooms(*)')
        .eq('user_id', user.id);

      const uniqueRooms = memberRooms?.map(m => m.study_rooms).filter(Boolean) || [];

      // Get member counts
      const roomsWithCounts = await Promise.all(
        uniqueRooms.map(async (room) => {
          const { count } = await supabase
            .from('room_members')
            .select('*', { count: 'exact', head: true })
            .eq('room_id', room.id);
          return { ...room, member_count: count || 0 };
        })
      );

      setRooms(roomsWithCounts);
    } catch (error) {
      console.error('Error loading rooms:', error);
      toast({
        title: 'Error',
        description: 'Failed to load study rooms',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  const createRoom = async () => {
    if (!roomName.trim()) {
      toast({
        title: 'Error',
        description: 'Please enter a room name',
        variant: 'destructive',
      });
      return;
    }

    try {
      const roomData: any = {
        name: roomName,
        description: roomDescription || null,
        is_public: false, // All rooms are now invite-only
        created_by: user.id, // RLS validates this matches auth.uid()
        // invite_code is auto-generated by database trigger
      };

      const { data: newRoom, error: roomError } = await supabase
        .from('study_rooms')
        .insert(roomData)
        .select()
        .single();

      if (roomError) throw roomError;

      // Add creator as member
      const { error: memberError } = await supabase
        .from('room_members')
        .insert({
          room_id: newRoom.id,
          user_id: user.id,
          role: 'owner',
        });

      if (memberError) throw memberError;

      toast({
        title: 'Success',
        description: 'Room created successfully!',
      });

      // Always show invite code dialog (all rooms are invite-only now)
      if (newRoom.invite_code) {
        setCurrentInviteCode(newRoom.invite_code);
        setShowInviteDialog(true);
      }

      setIsCreateOpen(false);
      setRoomName('');
      setRoomDescription('');
      loadRooms();
    } catch (error) {
      console.error('Error creating room:', error);
      toast({
        title: 'Error',
        description: 'Failed to create room',
        variant: 'destructive',
      });
    }
  };

  const joinRoom = async (roomId: string) => {
    try {
      const { error } = await supabase
        .from('room_members')
        .insert({
          room_id: roomId,
          user_id: user.id,
        });

      if (error) {
        if (error.message.includes('duplicate')) {
          // Already a member, just open the room
          const room = rooms.find(r => r.id === roomId);
          if (room) setSelectedRoom(room);
          return;
        }
        throw error;
      }

      toast({
        title: 'Success',
        description: 'Joined room successfully',
      });

      const room = rooms.find(r => r.id === roomId);
      if (room) setSelectedRoom(room);
    } catch (error) {
      console.error('Error joining room:', error);
      toast({
        title: 'Error',
        description: 'Failed to join room',
        variant: 'destructive',
      });
    }
  };

  const [joinCode, setJoinCode] = useState('');

  const joinByInviteCode = async () => {
    if (!joinCode.trim()) {
      toast({
        title: 'Error',
        description: 'Please enter a join code',
        variant: 'destructive',
      });
      return;
    }

    try {
      const { data: room, error: roomError } = await supabase
        .from('study_rooms')
        .select('*')
        .eq('invite_code', joinCode.toUpperCase())
        .single();

      if (roomError || !room) {
        toast({
          title: 'Error',
          description: 'Invalid join code',
          variant: 'destructive',
        });
        return;
      }

      await joinRoom(room.id);
      setIsJoinOpen(false);
      setJoinCode('');
    } catch (error) {
      console.error('Error joining by invite:', error);
      toast({
        title: 'Error',
        description: 'Failed to join room',
        variant: 'destructive',
      });
    }
  };

  const copyInviteCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(code);
    toast({
      title: 'Copied!',
      description: 'Invite code copied to clipboard',
    });
    setTimeout(() => setCopiedCode(null), 2000);
  };

  const copyInviteLink = (code: string) => {
    const inviteLink = `${window.location.origin}?invite=${code}`;
    navigator.clipboard.writeText(inviteLink);
    toast({
      title: 'Copied!',
      description: 'Invite link copied to clipboard',
    });
  };

  if (selectedRoom) {
    return (
      <StudyRoomInterface
        room={selectedRoom}
        user={user}
        onBack={() => {
          setSelectedRoom(null);
          loadRooms();
        }}
      />
    );
  }

  return (
    <div className="container mx-auto p-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-3xl font-bold">Study Rooms</h1>
          <p className="text-muted-foreground">Join rooms with invite codes to collaborate</p>
        </div>
        <div className="flex gap-2">
          <Dialog open={isJoinOpen} onOpenChange={setIsJoinOpen}>
            <DialogTrigger asChild>
              <Button variant="outline">
                <Lock className="mr-2 h-4 w-4" />
                Join Room
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Join Room</DialogTitle>
                <DialogDescription>
                  Enter the join code to access a study room
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4">
                <div>
                  <Label>Join Code</Label>
                  <Input
                    placeholder="Enter join code"
                    value={joinCode}
                    onChange={(e) => setJoinCode(e.target.value.toUpperCase())}
                    maxLength={8}
                  />
                </div>
                <Button onClick={joinByInviteCode} className="w-full">
                  Join Room
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="mr-2 h-4 w-4" />
                Create Room
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create Study Room</DialogTitle>
                <DialogDescription>
                  A unique join code will be generated for your room
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4">
                <div>
                  <Label>Room Name</Label>
                  <Input
                    placeholder="e.g., Calculus Study Group"
                    value={roomName}
                    onChange={(e) => setRoomName(e.target.value)}
                  />
                </div>
                <div>
                  <Label>Description (Optional)</Label>
                  <Textarea
                    placeholder="What's this room about?"
                    value={roomDescription}
                    onChange={(e) => setRoomDescription(e.target.value)}
                  />
                </div>
                <Button onClick={createRoom} className="w-full">
                  Create Room
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          {/* Invite Code Success Dialog */}
          <Dialog open={showInviteDialog} onOpenChange={setShowInviteDialog}>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Room Created Successfully!</DialogTitle>
                <DialogDescription>
                  Share this join code with others to join your room
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4">
                <div className="p-4 bg-muted rounded-lg">
                  <Label className="text-sm text-muted-foreground mb-2">Join Code</Label>
                  <div className="flex items-center gap-2 mt-2">
                    <code className="flex-1 text-2xl font-bold text-center py-3 px-4 bg-background rounded border">
                      {currentInviteCode}
                    </code>
                    <Button
                      size="icon"
                      variant="outline"
                      onClick={() => copyInviteCode(currentInviteCode)}
                    >
                      {copiedCode === currentInviteCode ? (
                        <Check className="h-4 w-4 text-green-500" />
                      ) : (
                        <Copy className="h-4 w-4" />
                      )}
                    </Button>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    className="flex-1"
                    onClick={() => copyInviteLink(currentInviteCode)}
                  >
                    <Share2 className="mr-2 h-4 w-4" />
                    Copy Join Link
                  </Button>
                  <Button
                    className="flex-1"
                    onClick={() => setShowInviteDialog(false)}
                  >
                    Done
                  </Button>
                </div>
              </div>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-12">Loading rooms...</div>
      ) : rooms.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <Users className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
            <h3 className="text-lg font-semibold mb-2">No rooms joined yet</h3>
            <p className="text-muted-foreground mb-4">Create or join a room with a join code</p>
            <div className="flex gap-2 justify-center">
              <Button onClick={() => setIsCreateOpen(true)}>
                <Plus className="mr-2 h-4 w-4" />
                Create Room
              </Button>
              <Button variant="outline" onClick={() => setIsJoinOpen(true)}>
                <Lock className="mr-2 h-4 w-4" />
                Join Room
              </Button>
            </div>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {rooms.map((room) => (
            <Card key={room.id} className="hover:shadow-lg transition-shadow">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <CardTitle className="flex items-center gap-2">
                      <Lock className="h-4 w-4" />
                      {room.name}
                    </CardTitle>
                    {room.description && (
                      <CardDescription className="mt-2">{room.description}</CardDescription>
                    )}
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div className="flex items-center text-sm text-muted-foreground">
                    <Users className="h-4 w-4 mr-1" />
                    {room.member_count || 0} members
                  </div>
                  <Button onClick={() => joinRoom(room.id)} size="sm">
                    Enter
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};