-- Seed Hospital Situations
INSERT INTO legal_situations (category_id, title_en, title_hi, title_mr, description_en, description_hi, description_mr, is_emergency, severity_level, keywords) VALUES
('3786f23b-a635-4a50-a90a-7b46bf9dd528', 'Denied Emergency Treatment', 'आपातकालीन उपचार से मना', 'आणीबाणी उपचारास नकार', 'Hospital refused to provide emergency medical treatment', 'अस्पताल ने आपातकालीन चिकित्सा उपचार देने से मना किया', 'रुग्णालयाने आणीबाणी वैद्यकीय उपचार देण्यास नकार दिला', true, 5, ARRAY['emergency', 'treatment', 'refused', 'hospital', 'MLC']),
('3786f23b-a635-4a50-a90a-7b46bf9dd528', 'Overcharged for Treatment', 'उपचार के लिए अधिक पैसे', 'उपचारासाठी जास्त पैसे', 'Hospital charged more than displayed rates or without transparency', 'अस्पताल ने प्रदर्शित दरों से अधिक शुल्क लिया', 'रुग्णालयाने प्रदर्शित दरांपेक्षा जास्त शुल्क आकारले', false, 3, ARRAY['overcharge', 'billing', 'rates', 'money']),
('3786f23b-a635-4a50-a90a-7b46bf9dd528', 'Medical Negligence', 'चिकित्सा लापरवाही', 'वैद्यकीय निष्काळजीपणा', 'Wrong treatment, misdiagnosis, or careless medical care', 'गलत इलाज, गलत निदान, या लापरवाह चिकित्सा देखभाल', 'चुकीचा उपचार, चुकीचे निदान, किंवा निष्काळजी वैद्यकीय सेवा', false, 4, ARRAY['negligence', 'wrong treatment', 'misdiagnosis']),
('3786f23b-a635-4a50-a90a-7b46bf9dd528', 'Body Not Released Without Payment', 'भुगतान के बिना शव नहीं दिया', 'पैसे दिल्याशिवाय मृतदेह दिला नाही', 'Hospital holding body until bills are paid', 'अस्पताल बिल का भुगतान होने तक शव को रोके हुए है', 'बिल भरल्याशिवाय रुग्णालय मृतदेह देत नाही', true, 5, ARRAY['body', 'death', 'payment', 'release']);

-- Seed Workplace Situations  
INSERT INTO legal_situations (category_id, title_en, title_hi, title_mr, description_en, description_hi, description_mr, is_emergency, severity_level, keywords) VALUES
('d63b5ef9-df40-4e9e-b50b-9414bf401b8a', 'Sexual Harassment at Work', 'कार्यस्थल पर यौन उत्पीड़न', 'कामाच्या ठिकाणी लैंगिक छळ', 'Experiencing unwanted sexual advances or harassment at workplace', 'कार्यस्थल पर अनचाहे यौन प्रस्ताव या उत्पीड़न का सामना', 'कामाच्या ठिकाणी अनिच्छित लैंगिक प्रस्ताव किंवा छळ', true, 5, ARRAY['sexual harassment', 'POSH', 'workplace', 'ICC']),
('d63b5ef9-df40-4e9e-b50b-9414bf401b8a', 'Salary Not Paid', 'वेतन नहीं मिला', 'पगार मिळाला नाही', 'Employer not paying salary on time or withholding wages', 'नियोक्ता समय पर वेतन नहीं दे रहा या रोक रहा है', 'नियोक्ता वेळेवर पगार देत नाही किंवा रोखून धरत आहे', false, 3, ARRAY['salary', 'wages', 'payment', 'delay']),
('d63b5ef9-df40-4e9e-b50b-9414bf401b8a', 'Wrongful Termination', 'गलत तरीके से नौकरी से निकाला', 'चुकीच्या पद्धतीने नोकरीवरून काढले', 'Fired without proper notice or valid reason', 'उचित नोटिस या वैध कारण के बिना निकाला गया', 'योग्य नोटीस किंवा वैध कारणाशिवाय काढून टाकले', false, 4, ARRAY['termination', 'fired', 'dismissal', 'notice']),
('d63b5ef9-df40-4e9e-b50b-9414bf401b8a', 'Unsafe Working Conditions', 'असुरक्षित कार्य स्थितियां', 'असुरक्षित कामाच्या परिस्थिती', 'Workplace lacks safety measures or hazardous environment', 'कार्यस्थल में सुरक्षा उपायों की कमी या खतरनाक वातावरण', 'कामाच्या ठिकाणी सुरक्षा उपायांचा अभाव किंवा धोकादायक वातावरण', false, 4, ARRAY['safety', 'hazard', 'injury', 'workplace']),
('d63b5ef9-df40-4e9e-b50b-9414bf401b8a', 'Discrimination at Work', 'कार्यस्थल पर भेदभाव', 'कामाच्या ठिकाणी भेदभाव', 'Facing discrimination based on caste, gender, religion, or disability', 'जाति, लिंग, धर्म या विकलांगता के आधार पर भेदभाव', 'जात, लिंग, धर्म किंवा अपंगत्वाच्या आधारावर भेदभाव', false, 4, ARRAY['discrimination', 'caste', 'gender', 'bias']);

-- Seed Women Safety Situations
INSERT INTO legal_situations (category_id, title_en, title_hi, title_mr, description_en, description_hi, description_mr, is_emergency, severity_level, keywords) VALUES
('6e2b5a6e-5c7c-4aac-a987-f890783672ad', 'Domestic Violence', 'घरेलू हिंसा', 'घरगुती हिंसा', 'Physical, emotional, or financial abuse by spouse or family', 'पति या परिवार द्वारा शारीरिक, भावनात्मक या आर्थिक दुर्व्यवहार', 'पती किंवा कुटुंबाद्वारे शारीरिक, भावनिक किंवा आर्थिक अत्याचार', true, 5, ARRAY['domestic violence', 'abuse', 'husband', 'family', 'DV']),
('6e2b5a6e-5c7c-4aac-a987-f890783672ad', 'Eve Teasing / Street Harassment', 'छेड़छाड़', 'छेडछाड', 'Unwanted comments, gestures, or stalking in public', 'सार्वजनिक स्थान पर अनचाही टिप्पणी, इशारे या पीछा करना', 'सार्वजनिक ठिकाणी अनिच्छित टिप्पण्या, हावभाव किंवा पाठलाग', false, 3, ARRAY['eve teasing', 'harassment', 'stalking', 'public']),
('6e2b5a6e-5c7c-4aac-a987-f890783672ad', 'Dowry Harassment', 'दहेज उत्पीड़न', 'हुंडा छळ', 'Demands for dowry or harassment related to dowry', 'दहेज की मांग या दहेज संबंधित उत्पीड़न', 'हुंड्याची मागणी किंवा हुंड्याशी संबंधित छळ', true, 5, ARRAY['dowry', 'harassment', 'demand', 'in-laws']),
('6e2b5a6e-5c7c-4aac-a987-f890783672ad', 'Cyber Harassment Against Women', 'महिलाओं के खिलाफ साइबर उत्पीड़न', 'महिलांविरुद्ध सायबर छळ', 'Online threats, morphed images, or harassment', 'ऑनलाइन धमकी, मॉर्फ्ड तस्वीरें या उत्पीड़न', 'ऑनलाइन धमक्या, मॉर्फ्ड फोटो किंवा छळ', false, 4, ARRAY['cyber', 'online', 'morphed', 'photos', 'threats']);

-- Seed Consumer Situations
INSERT INTO legal_situations (category_id, title_en, title_hi, title_mr, description_en, description_hi, description_mr, is_emergency, severity_level, keywords) VALUES
('a1a310b2-bb1a-4752-919a-ec183ddaa43d', 'Defective Product', 'खराब उत्पाद', 'सदोष उत्पादन', 'Purchased product is defective or not as described', 'खरीदा गया उत्पाद खराब है या विवरण के अनुसार नहीं', 'विकत घेतलेले उत्पादन सदोष आहे किंवा वर्णनानुसार नाही', false, 2, ARRAY['defective', 'product', 'refund', 'exchange']),
('a1a310b2-bb1a-4752-919a-ec183ddaa43d', 'Service Not Rendered', 'सेवा नहीं दी गई', 'सेवा दिली नाही', 'Paid for service but not received or poor quality', 'सेवा के लिए भुगतान किया लेकिन नहीं मिली या खराब गुणवत्ता', 'सेवेसाठी पैसे दिले पण मिळाली नाही किंवा खराब दर्जा', false, 2, ARRAY['service', 'payment', 'quality', 'refund']),
('a1a310b2-bb1a-4752-919a-ec183ddaa43d', 'E-commerce Fraud', 'ऑनलाइन धोखाधड़ी', 'ऑनलाइन फसवणूक', 'Cheated by online seller or fake website', 'ऑनलाइन विक्रेता या नकली वेबसाइट द्वारा धोखा', 'ऑनलाइन विक्रेता किंवा बनावट वेबसाइटद्वारे फसवणूक', false, 3, ARRAY['ecommerce', 'online', 'fraud', 'fake']),
('a1a310b2-bb1a-4752-919a-ec183ddaa43d', 'Bank/Insurance Complaint', 'बैंक/बीमा शिकायत', 'बँक/विमा तक्रार', 'Issues with bank charges, insurance claim rejection', 'बैंक शुल्क, बीमा दावा अस्वीकृति की समस्या', 'बँक शुल्क, विमा दावा नाकारण्याची समस्या', false, 3, ARRAY['bank', 'insurance', 'claim', 'charges']);

-- Seed Traffic Situations
INSERT INTO legal_situations (category_id, title_en, title_hi, title_mr, description_en, description_hi, description_mr, is_emergency, severity_level, keywords) VALUES
('028e145f-215f-47b0-b3ff-8142c80baa50', 'Challan Issued Wrongly', 'गलत चालान', 'चुकीचा दंड', 'Received traffic fine for violation not committed', 'न किए गए उल्लंघन के लिए यातायात जुर्माना मिला', 'न केलेल्या उल्लंघनासाठी वाहतूक दंड मिळाला', false, 2, ARRAY['challan', 'fine', 'wrong', 'traffic']),
('028e145f-215f-47b0-b3ff-8142c80baa50', 'Road Accident', 'सड़क दुर्घटना', 'रस्ता अपघात', 'Involved in or witnessed a road accident', 'सड़क दुर्घटना में शामिल या गवाह', 'रस्ता अपघातात सहभागी किंवा साक्षीदार', true, 5, ARRAY['accident', 'road', 'injury', 'hit']),
('028e145f-215f-47b0-b3ff-8142c80baa50', 'Bribe Demand by Traffic Police', 'यातायात पुलिस द्वारा रिश्वत मांगी', 'वाहतूक पोलिसांनी लाच मागितली', 'Traffic police asking for bribe to avoid challan', 'चालान से बचने के लिए यातायात पुलिस रिश्वत मांग रही', 'चलान टाळण्यासाठी वाहतूक पोलीस लाच मागत आहेत', false, 3, ARRAY['bribe', 'traffic', 'police', 'corruption']),
('028e145f-215f-47b0-b3ff-8142c80baa50', 'Vehicle Towed Without Reason', 'बिना कारण गाड़ी उठाई', 'कारणाशिवाय वाहन उचलले', 'Vehicle towed when legally parked', 'कानूनी रूप से पार्क होने पर भी गाड़ी उठा ली गई', 'कायदेशीररित्या पार्क असतानाही वाहन उचलले', false, 2, ARRAY['towed', 'vehicle', 'parked', 'impound']);

-- Seed Property Situations
INSERT INTO legal_situations (category_id, title_en, title_hi, title_mr, description_en, description_hi, description_mr, is_emergency, severity_level, keywords) VALUES
('8f24587f-21ec-4fe1-8010-c6399abc8584', 'Tenant Rights Violation', 'किरायेदार अधिकार उल्लंघन', 'भाडेकरूच्या हक्कांचे उल्लंघन', 'Landlord refusing to return deposit or illegal eviction', 'मकान मालिक जमा राशि वापस नहीं कर रहा या अवैध बेदखली', 'जमीनमालक ठेव परत करत नाही किंवा बेकायदेशीर बेदखली', false, 3, ARRAY['tenant', 'landlord', 'deposit', 'eviction', 'rent']),
('8f24587f-21ec-4fe1-8010-c6399abc8584', 'Property Fraud/Cheating', 'संपत्ति धोखाधड़ी', 'मालमत्ता फसवणूक', 'Cheated in property purchase or fake documents', 'संपत्ति खरीद में धोखा या नकली दस्तावेज', 'मालमत्ता खरेदीत फसवणूक किंवा बनावट कागदपत्रे', false, 4, ARRAY['property', 'fraud', 'documents', 'cheating']),
('8f24587f-21ec-4fe1-8010-c6399abc8584', 'Encroachment on Land', 'जमीन पर अतिक्रमण', 'जमिनीवर अतिक्रमण', 'Someone has illegally occupied your land', 'किसी ने आपकी जमीन पर अवैध कब्जा कर लिया है', 'कोणीतरी तुमच्या जमिनीवर बेकायदेशीर कब्जा केला आहे', false, 4, ARRAY['encroachment', 'land', 'illegal', 'occupation']),
('8f24587f-21ec-4fe1-8010-c6399abc8584', 'Builder/Developer Issues', 'बिल्डर/डेवलपर समस्या', 'बिल्डर/डेव्हलपर समस्या', 'Delayed possession, poor construction, or cheating', 'देरी से कब्जा, खराब निर्माण या धोखाधड़ी', 'विलंबित ताबा, खराब बांधकाम किंवा फसवणूक', false, 3, ARRAY['builder', 'developer', 'possession', 'construction', 'RERA']);

-- Seed Government Situations
INSERT INTO legal_situations (category_id, title_en, title_hi, title_mr, description_en, description_hi, description_mr, is_emergency, severity_level, keywords) VALUES
('77507a2c-269c-450e-96f6-7a06668aa8fd', 'Ration Card Issues', 'राशन कार्ड समस्या', 'रेशन कार्ड समस्या', 'Denied ration or ration card related issues', 'राशन नहीं मिला या राशन कार्ड संबंधित समस्या', 'रेशन मिळाले नाही किंवा रेशन कार्ड संबंधित समस्या', false, 3, ARRAY['ration', 'card', 'PDS', 'food']),
('77507a2c-269c-450e-96f6-7a06668aa8fd', 'Corruption in Government Office', 'सरकारी कार्यालय में भ्रष्टाचार', 'सरकारी कार्यालयात भ्रष्टाचार', 'Official demanding bribe for service', 'अधिकारी सेवा के लिए रिश्वत मांग रहा है', 'अधिकारी सेवेसाठी लाच मागत आहे', false, 3, ARRAY['corruption', 'bribe', 'government', 'official']),
('77507a2c-269c-450e-96f6-7a06668aa8fd', 'Pension Not Received', 'पेंशन नहीं मिली', 'पेन्शन मिळाली नाही', 'Pension delayed or stopped without reason', 'पेंशन में देरी या बिना कारण रोक', 'पेन्शनला विलंब किंवा कारणाशिवाय थांबवले', false, 3, ARRAY['pension', 'delay', 'senior', 'retired']),
('77507a2c-269c-450e-96f6-7a06668aa8fd', 'Aadhar/PAN Card Issues', 'आधार/पैन कार्ड समस्या', 'आधार/पॅन कार्ड समस्या', 'Problems with Aadhar enrollment or corrections', 'आधार नामांकन या सुधार में समस्या', 'आधार नोंदणी किंवा दुरुस्तीत समस्या', false, 2, ARRAY['aadhar', 'PAN', 'card', 'enrollment']);