// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwqteupkdkkmigvajdrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3cXRldXBrZGtrbWlndmFqZHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzU4MjksImV4cCI6MjA2ODE1MTgyOX0.3HXdgQ3qcFgEEjnghcCx0Lcdt0UYP9FdiWZI9Bk_LIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});