// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rwqteupkdkkmigvajdrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3cXRldXBrZGtrbWlndmFqZHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzU4MjksImV4cCI6MjA2ODE1MTgyOX0.3HXdgQ3qcFgEEjnghcCx0Lcdt0UYP9FdiWZI9Bk_LIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: We intentionally avoid importing the generated Database types here to keep TypeScript
// builds stable/performance-friendly in constrained environments.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
